# scipy.odr.OdrStop

> 原文：[https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.odr.OdrStop.html#scipy.odr.OdrStop](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.odr.OdrStop.html#scipy.odr.OdrStop)

```py
exception scipy.odr.OdrStop
```

异常停止拟合。

你可以在你的目标函数中引发这个异常，告诉[`odr`](odr-function.html#scipy.odr.odr "scipy.odr.odr")停止拟合。

```py
with_traceback()
```

`Exception.with_traceback(tb)` – 设置`self.__traceback__`为`tb`并返回`self`。
