- en: numpy.geterrcall
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: numpy.geterrcall
- en: 原文：[https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html](https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html](https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html)
- en: '[PRE0]'
  id: totrans-2
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: Return the current callback function used on floating-point errors.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 返回当前用于浮点错误的回调函数。
- en: When the error handling for a floating-point error (one of “divide”, “over”,
    “under”, or “invalid”) is set to ‘call’ or ‘log’, the function that is called
    or the log instance that is written to is returned by [`geterrcall`](#numpy.geterrcall
    "numpy.geterrcall"). This function or log instance has been set with [`seterrcall`](numpy.seterrcall.html#numpy.seterrcall
    "numpy.seterrcall").
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: 当浮点错误（“divide”、“over”、“under”或“invalid”之一）的错误处理设置为“call”或“log”时，返回使用[`geterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.geterrcall.html)设置的函数或日志实例。此函数或日志实例已通过[`seterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.seterrcall.html)设置。
- en: 'Returns:'
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: 返回值：
- en: '**errobj**callable, log instance or None'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: '**errobj**可调用对象、日志实例或None'
- en: The current error handler. If no handler was set through [`seterrcall`](numpy.seterrcall.html#numpy.seterrcall
    "numpy.seterrcall"), `None` is returned.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 当前错误处理程序。如果未通过[`seterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.seterrcall.html)设置处理程序，则返回None。
- en: See also
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 另请参见
- en: '[`seterrcall`](numpy.seterrcall.html#numpy.seterrcall "numpy.seterrcall"),
    [`seterr`](numpy.seterr.html#numpy.seterr "numpy.seterr"), [`geterr`](numpy.geterr.html#numpy.geterr
    "numpy.geterr")'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '[`seterrcall`](https://numpy.org/doc/1.26/reference/generated/numpy.seterrcall.html)、[`seterr`](https://numpy.org/doc/1.26/reference/generated/numpy.seterr.html)和[`geterr`](https://numpy.org/doc/1.26/reference/generated/numpy.geterr.html)'
- en: Notes
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 注意事项
- en: For complete documentation of the types of floating-point exceptions and treatment
    options, see [`seterr`](numpy.seterr.html#numpy.seterr "numpy.seterr").
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 关于浮点异常类型和处理选项的完整文档，请参阅[`seterr`](https://numpy.org/doc/1.26/reference/generated/numpy.seterr.html)。
- en: Examples
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 示例
- en: '[PRE1]'
  id: totrans-13
  prefs: []
  type: TYPE_PRE
  zh: '[PRE1]'
- en: '[PRE2]'
  id: totrans-14
  prefs: []
  type: TYPE_PRE
  zh: '[PRE2]'
- en: '[PRE3]'
  id: totrans-15
  prefs: []
  type: TYPE_PRE
  zh: '[PRE3]'
