- en: numpy.exceptions.TooHardError
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://numpy.org/doc/1.26/reference/generated/numpy.exceptions.TooHardError.html](https://numpy.org/doc/1.26/reference/generated/numpy.exceptions.TooHardError.html)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: max_work was exceeded.
  prefs: []
  type: TYPE_NORMAL
- en: This is raised whenever the maximum number of candidate solutions to consider
    specified by the `max_work` parameter is exceeded. Assigning a finite number to
    max_work may have caused the operation to fail.
  prefs: []
  type: TYPE_NORMAL
