- en: numpy.testing.assert_raises
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://numpy.org/doc/1.26/reference/generated/numpy.testing.assert_raises.html](https://numpy.org/doc/1.26/reference/generated/numpy.testing.assert_raises.html)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: Fail unless an exception of class exception_class is thrown by callable when
    invoked with arguments args and keyword arguments kwargs. If a different type
    of exception is thrown, it will not be caught, and the test case will be deemed
    to have suffered an error, exactly as for an unexpected exception.
  prefs: []
  type: TYPE_NORMAL
- en: 'Alternatively, [`assert_raises`](#numpy.testing.assert_raises "numpy.testing.assert_raises")
    can be used as a context manager:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE2]'
  prefs: []
  type: TYPE_PRE
- en: is equivalent to
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE3]'
  prefs: []
  type: TYPE_PRE
