["```py\nexception pandas.errors.DuplicateLabelError\n```", "```py\n>>> s = pd.Series([0, 1, 2], index=['a', 'b', 'c']).set_flags(\n...     allows_duplicate_labels=False\n... )\n>>> s.reindex(['a', 'a', 'b'])\nTraceback (most recent call last):\n  ...\nDuplicateLabelError: Index has duplicates.\n positions\nlabel\na        [0, 1] \n```"]