["```py\nexception pandas.errors.UnsupportedFunctionCall\n```", "```py\n>>> df = pd.DataFrame({\"A\": [0, 0, 1, 1],\n...                    \"B\": [\"x\", \"x\", \"z\", \"y\"],\n...                    \"C\": [1, 2, 3, 4]}\n...                   )\n>>> np.cumsum(df.groupby([\"A\"]))\nTraceback (most recent call last):\nUnsupportedFunctionCall: numpy operations are not valid with groupby.\nUse .groupby(...).cumsum() instead \n```"]