["```py\nexception scipy.linalg.LinAlgError\n```", "```py\n>>> from numpy import linalg as LA\n>>> LA.inv(np.zeros((2,2)))\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n File \"...linalg.py\", line 350,\n in inv return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))\n File \"...linalg.py\", line 249,\n in solve\n raise LinAlgError('Singular matrix')\nnumpy.linalg.LinAlgError: Singular matrix \n```", "```py\nwith_traceback()\n```"]